### PR TITLE
Use GitHub SSH keys

### PR DESCRIPTION
**Pull request by JONTTM**

### CODE REVIEW

**Comment by JONTTM** [comment]
@leighmacdonald this is deployed

**Review by leighmacdonald — CHANGES_REQUESTED** [review]
Tying into github for ssh keys is not an improvement imo, I do not want to introduce dynamic keys and a reliance on a 3rd party service. 

Additionally I don't want multiple unrelated keys being deployed for various reasons, see: https://github.com/leighmacdonald.keys

**Comment by JONTTM** [comment]
> Tying into github for ssh keys is not an improvement imo, I do not want to introduce dynamic keys and a reliance on a 3rd party service.
> 
> Additionally I don't want multiple unrelated keys being deployed for various reasons, see: https://github.com/leighmacdonald.keys

Ok @leighmacdonald I will change your key back to the permanent one. But I think using GitHub for the other keys is fine.

**Comment by JONTTM** [comment]
The changes have been made on the private repo

**Review by leighmacdonald — APPROVED** [review]

**Pull request merged**
